#!/usr/bin/env python

import sys

def printUsage():
  print "Usage: %s <pallete-file>" % sys.argv[0]

def chunks(thing, size):
  for i in range(0, len(thing), size):
    yield thing[i:i+size]

def main():
  if len(sys.argv) < 2:
    printUsage()
    sys.exit(1)

  path = sys.argv[1]
  fp = open(path, "r")

  names = ()

  for line in fp:
    (html, name) = line.split("=")
    html = html.strip()
    name = name.strip().upper().replace(" ", "_")
    name = name.replace("'", "")
    components = tuple(chunks(html, 2))
    components = tuple(map(lambda x: int(x, 16) / 255.0, components))
    components = components + (1,)
    names += (name,)
    print "%s = vrend.Color%s" % (name, components)

  print "PALETTE = (%s)" % ", ".join(names)


if __name__ == "__main__":
  main()
